### ISSUE TITLE
20 fu ron

### ISSUE THREAD

**Issue by NailoTB** [marcoskwkm/riichi#1]
Currently, the Riichi Trainer includes the 20fu ron as one of the cases. In standard rules, this is not possible to occur. Would it possible to remove it from the pool?

Thanks.

**Comment by marcoskwkm** [comment]
Thanks for bringing attention to this.

I extracted the list of scores from the table in the [WRC 2022 rulebook](https://www.worldriichi.org/wrc-rules), which curiously also includes the 1 han 20 fu case.

I was under the impression that some rulesets allow a 20 fu ron but from a quick Google search I couldn't find any such instance, so I removed these scores from the trainer.
